### PR TITLE
Tweak gnome settings and extensions

### PR DESCRIPTION
**Pull request by Chrysostomus**
This pull request does not include manjaro update extension yet

### CODE REVIEW

**Comment by Ste74** [comment]
Can you change the branch in devel ?

**Comment by Chrysostomus** [comment]
I think I can

**Comment by Chrysostomus** [comment]
It is done, it seems.

**Comment by Chrysostomus** [comment]
Can you elaborate? The purpose of the the desktop file is to prevent pamac-updater from autostarting in gnome. Does the update also achieve this goal?

**Comment by philmmanjaro** [comment]
No, they dont: https://github.com/manjaro/pamac/blob/master/data/applications/pamac-tray.desktop Why is it important not to autostart in Gnome?

**Comment by Chrysostomus** [comment]
Current gnome setup has extremely high ram usage, and replacing those notifications with update notifier integrated into gnome shell extension saves about 40 Mb ram and has other advantages. Also, gnomes default policy is to hide system tray in bottom left corner, which makes pamac icon too inaccessible to be useful. 

It is not absolutely viral, but it is something we discussed we would try in this forum thread. Most of the code for the manjaro fork of the extension is now ready.

**Comment by Chrysostomus** [comment]
@philmmanjaro  40Mb is not that big in itself, but still a major part of making the edition lighter. The previous release had about 600Mb ram usage and 3second startup time (of which many users complained). That limits the breadth of potential userbase. With these tweaks it whould be down to 400Mb and about 5 second startup.
 
To see more about the proposed alternative, see two last posts here:

https://forum.manjaro.org/t/gnome-edition-improvement-focus/22240/56

manjaro update notifier now also notifies about kernel becoming eol (to replace msm_notifier) and has potential to notify about critical updates announced in forum announcements (if tag those somehow like I suggested in the thread). Latter functionality had been requested from manjaro in other threads seeking to improve manjaros beginner firendliness.

The extension integrates with pamac, gnome-shell and uses existing update-notifier package made for pacui/pacli. I think we should give it a shot.

**Comment by Ste74** [comment]
I also create a dev gnome-settings pkg to do this and install in local for our user to test it .. But do you mean with your comment with pamac @philmmanjaro ? pamac-tray is not a dependence for pamac ?

**Comment by Ste74** [comment]
Well @philmmanjaro created a dev pkg to for testing and development purpose ..merge this in devel branch and i will push in a -dev pkg ..

**Comment by Ste74** [comment]
@Chrysostomus add here your extra dependence https://github.com/manjaro/packages-community/commit/834e249ec1340a331b442642c826200f576091ba
i'm curios to see what happen 😄

**Comment by Chrysostomus** [comment]
The manjaro-update indicator extension package is still a bit broken. I haven't written Javascript before, so takes a while to figure out. I'll try to get it working tonight. We could also just use the original aur package and point it to right scripts in the settings... But then we couldn't change the icons, and we can't keep the arch ones on official edition...

**Comment by Ste74** [comment]
Keep your time don't worry ..

**Pull request merged**
